language: ruby

sudo: required

dist: trusty

before_install: skip

install: skip

before_script:
  - curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > ./docker-compose
  - sudo mv ./docker-compose /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

script: ./script/docker-build-and-push
